services:
  nexus: #builds the nexus repo at http://localhost:8081
    build:
      context: ./
      dockerfile: Dockerfile-nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/opt/nexus
  
  runner: #builds the runner
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - runner-data:/home/GHA/actions-runner

volumes:
  nexus-data:
  runner-data: