FROM ubuntu:20.04

# Create the "nexus" user and group, and set up Nexus directories
RUN addgroup --system nexus && \
    adduser --system --ingroup nexus nexus && \
    mkdir -p /opt/nexus

# Install required packages and download Nexus
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install wget openjdk-8-jdk -y && \
    wget https://download.sonatype.com/nexus/3/nexus-3.64.0-04-unix.tar.gz -P /opt/nexus/ && \
    tar -xvf /opt/nexus/nexus-3.64.0-04-unix.tar.gz -C /opt/nexus/ && \
    rm -f /opt/nexus/nexus-3.64.0-04-unix.tar.gz

# Set ownership for the Nexus installation directory
RUN chown -R nexus:nexus /opt/nexus

# Runs on port 8081
EXPOSE 8081

# Switch to the "nexus"
USER nexus

# start Nexus
ENTRYPOINT ["/opt/nexus/nexus-3.64.0-04/bin/nexus", "run"]