apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
  namespace: bootcamp
  labels:
    app: bootcamp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
      - name: runner
        image: docker.io/beebecomebigbee/runner:latest
        ports:
        - containerPort: 80
